[2022-05-29 08:27:09,798] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.get_data scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 08:27:09,804] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.get_data scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 08:27:09,804] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 08:27:09,804] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-29 08:27:09,804] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 08:27:09,812] {taskinstance.py:1378} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2022-05-28 00:00:00+00:00
[2022-05-29 08:27:09,814] {standard_task_runner.py:52} INFO - Started process 65 to run task
[2022-05-29 08:27:09,816] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Etl', 'get_data', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp5iolqdz1', '--error-file', '/tmp/tmp_k61tdfo']
[2022-05-29 08:27:09,816] {standard_task_runner.py:80} INFO - Job 41: Subtask get_data
[2022-05-29 08:27:09,846] {task_command.py:370} INFO - Running <TaskInstance: Etl.get_data scheduled__2022-05-28T00:00:00+00:00 [running]> on host b7bcf2b221fa
[2022-05-29 08:27:09,898] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Etl
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T00:00:00+00:00
[2022-05-29 08:27:10,123] {base.py:68} INFO - Using connection ID 'tutorial_pg_conn' for task execution.
[2022-05-29 08:27:10,128] {python.py:173} INFO - Done. Returned value was: None
[2022-05-29 08:27:10,146] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=Etl, task_id=get_data, execution_date=20220528T000000, start_date=20220529T082709, end_date=20220529T082710
[2022-05-29 08:27:10,187] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-29 08:27:10,214] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
